# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  docker: circleci/docker@1.7.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: donetapp:latest
    steps:
      - docker/build:
          image: dotnet-sample 
          debug: false 
          lint-dockerfile: false 
          treat-warnings-as-errors: false 
          dockerfile: samples/dotnetapp/Dockerfile 
          docker-context: samples/dotnetapp 

workflows:
  example-workflow:
    jobs:
      - example-job
